# Cocogitto Configuration
# for Conventional Commits and Changelog Generation.
# See https://github.com/cocogitto/cocogitto
# `cog --version` -> "cog 6.1.0"
# try `curl https://gist.githubusercontent.com/bradobro/44f0919652642ea92bde6270b3b602ab/raw/cog.toml > cog.toml`

branch_whitelist = []
disable_bump_commit = false
disable_changelog = false
from_latest_tag = false
generate_mono_repository_global_tag = true
ignore_merge_commits = true
post_bump_hooks = []
post_package_bump_hooks = []
pre_bump_hooks = []
pre_package_bump_hooks = []
skip_ci = "[skip ci]"
skip_untracked = false
tag_prefix = "v"

# install with `cog install-hook -a -o`
[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
cog check
"""

[commit_types]
begin = { changelog_title = "Work Begun", omit_from_changelog = true }
wip = { changelog_title = "Work in Process", omit_from_changelog = true }
red = { changelog_title = "RED: TDD WIP", omit_from_changelog = true }
green = { changelog_title = "GREEN: TDD WIP", omit_from_changelog = true }
chore = { changelog_title = "chores", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
authors = [
  { signature = "brad.olson@movedbylight.com", username = "bradobro" }
]


[bump_profiles]

[packages]
